export const preloadedCannedLaborData = [
  {
    name: "Wrap Installation",
    category: "Vinyl Wrap",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Tint Installation",
    category: "Window Tint",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "PPF Installation",
    category: "Paint Protection Film",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Body Repair",
    category: "Collision Repair",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Tint Removal",
    category: "Window Tint",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Wrap Removal",
    category: "Vinyl Wrap",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "PPF Removal",
    category: "Paint Protection Film",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Coating Installation",
    category: "Ceramic Coating",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Paint Installation",
    category: "Paint",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Light Installation",
    category: "Lighting",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Audio Installation",
    category: "Audio & Electronics",
    notes: null,
    hours: 1,
    charge: 100,
  },
  {
    name: "Detailing",
    category: "Detailing",
    notes: null,
    hours: 1,
    charge: 100,
  },
];

export const preloadedCannedServiceData = [
  { name: "Full Vehicle Wrap", category: "Vinyl Wrap" },
  { name: "Rally Stripes", category: "Vinyl Wrap" },
  { name: "Hood Wrap", category: "Vinyl Wrap" },
  { name: "Door Jambs", category: "Vinyl Wrap" },
  { name: "Partial Vehicle Wrap", category: "Vinyl Wrap" },
  { name: "Roof Wrap", category: "Vinyl Wrap" },
  { name: "Door Handle Wrap", category: "Vinyl Wrap" },
  { name: "Side Mirror Wrap", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Window Trim", category: "Vinyl Wrap" },
  { name: "Camo Wrap", category: "Vinyl Wrap" },
  { name: "Trunk Wrap", category: "Vinyl Wrap" },
  { name: "Spoiler Wrap", category: "Vinyl Wrap" },
  { name: "Decal Installation", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Grille", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Fog Light", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Side Mirror", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Fender", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Door", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Trunk", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Emblem", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Door Handle", category: "Vinyl Wrap" },
  { name: "Chrome Delete - Roof Rail", category: "Vinyl Wrap" },
  { name: "Wrap & Glue Removal", category: "Vinyl Wrap" },
  { name: "Full Vehicle Window Tint", category: "Window Tint" },
  { name: "Frt 2 Window Tint", category: "Window Tint" },
  { name: "Frt Windshield Window Tint", category: "Window Tint" },
  { name: "Rear Windshield Window Tint", category: "Window Tint" },
  { name: "Window Tint Removal", category: "Window Tint" },
  { name: "Sunroof Tint", category: "Window Tint" },
  { name: "Sunstrip Tint", category: "Window Tint" },
  { name: "Quarter Window Tint Removal", category: "Window Tint" },
  { name: "PPF - Full Vehicle", category: "Paint Protection Film" },
  { name: "PPF - Full Front End", category: "Paint Protection Film" },
  { name: "PPF - Partial Front End", category: "Paint Protection Film" },
  { name: "PPF - Individual Panel", category: "Paint Protection Film" },
  { name: "PPF - Headlights", category: "Paint Protection Film" },
  { name: "PPF - Interior Panel", category: "Paint Protection Film" },
  { name: "PPF - Removal", category: "Paint Protection Film" },
  { name: "Ambient Lighting", category: "Lighting" },
  { name: "HID Lighting", category: "Lighting" },
  { name: "Starlight Headliner", category: "Lighting" },
  { name: "Underglow", category: "Lighting" },
  { name: "Rock Lighting", category: "Lighting" },
  { name: "Puddle Lights", category: "Lighting" },
  { name: "Demon Eyes", category: "Lighting" },
  { name: "Powder Coat", category: "Wheels & Tires" },
  { name: "Curb Rash Repair", category: "Wheels & Tires" },
  { name: "Wheel Refinishing", category: "Wheels & Tires" },
  { name: "Wheel Straightening", category: "Wheels & Tires" },
  { name: "Wheel Welding", category: "Wheels & Tires" },
  { name: "Dent Repair", category: "Collision Repair" },
  { name: "Sanding", category: "Collision Repair" },
  { name: "Paintless Dent Repair", category: "Collision Repair" },
  { name: "Car Wash", category: "Detailing" },
  { name: "Interior Detailing", category: "Detailing" },
  { name: "Interior & Exterior Detail", category: "Detailing" },
  { name: "Interior Shampoo", category: "Detailing" },
  { name: "Pet Hair Removal", category: "Detailing" },
  { name: "Headlight Restoration", category: "Detailing" },
  { name: "Paint Correction - 1 Step", category: "Detailing" },
  { name: "Paint Correction - 2 Step", category: "Detailing" },
  { name: "Paint Correction - 3 Step", category: "Detailing" },
  { name: "Engine Cleaning", category: "Detailing" },
  { name: "Steam Cleaning", category: "Detailing" },
  { name: "Leather Trimming", category: "Detailing" },
  { name: "Splitter Installation", category: "Parts & Accessories" },
  { name: "Spoiler Installation", category: "Parts & Accessories" },
  { name: "Body Kit Installation", category: "Parts & Accessories" },
  { name: "Aftermarket Part Installation", category: "Parts & Accessories" },
  { name: "Paint Ceramic Coating", category: "Ceramic Coating" },
  { name: "Film Ceramic Coating", category: "Ceramic Coating" },
  { name: "Trim Ceramic Coating", category: "Ceramic Coating" },
  { name: "Leather Ceramic Coating", category: "Ceramic Coating" },
  { name: "Caliper Paint", category: "Paint" },
  { name: "Wheel Paint", category: "Paint" },
  { name: "Panel Paint", category: "Paint" },
  { name: "Emblem Paint", category: "Paint" },
  { name: "Car Seat Repair", category: "Upholstery" },
  { name: "Leather Repair", category: "Upholstery" },
  { name: "Interior Leather Upgrade", category: "Upholstery" },
];

export const preloadedCategories = [
  { name: "Vinyl Wrap" },
  { name: "Window Tint" },
  { name: "Paint Protection Film" },
  { name: "Lighting" },
  { name: "Wheels & Tires" },
  { name: "Collision Repair" },
  { name: "Detailing" },
  { name: "Parts & Accessories" },
  { name: "Ceramic Coating" },
  { name: "Paint" },
  { name: "Upholstery" },
];
