/**
 * AUTO-GENERATED — do not edit manually.
 * Run: yarn generate:search
 * Generated: 2026-08-20T16:17:22.806Z
 * Source: src/app
 */
import type { RoutePermissionKey } from "./routePermissionKeys";
import type { RouteFeatureKey } from "./routeFeatureKeys";

export type SearchItemType = "page" | "form" | "settings" | "section";

export interface SearchItem {
  id: string;
  label: string;
  description?: string;
  href: string;
  type: SearchItemType;
  keywords: string[];
  /** User-permission key(s) guarding this route, resolved from ROUTE_PERMISSIONS_MAP at generation time. */
  permissionKey?: RoutePermissionKey;
  /** Company feature key(s) guarding this route, resolved from FEATURE_PERMISSIONS_MAP at generation time. */
  featureKey?: RouteFeatureKey;
}

export const generatedRegistry: SearchItem[] = [
  {
    id: "clickup-reporting",
    label: "Clickup › Reporting",
    href: "/clickup/reporting",
    type: "page",
    keywords: ["clickup", "reporting"],
  },
  {
    id: "dashboard",
    label: "Dashboard",
    href: "/dashboard",
    type: "page",
    keywords: ["dashboard"],
    description: "Dashboard",
  },
  {
    id: "dashboard-client",
    label: "Directory - Client",
    href: "/dashboard/client",
    type: "page",
    keywords: ["dashboard", "client", "directory"],
    description: "Manage your clients",
    permissionKey: "clientDirectory",
    featureKey: "clientDirectory",
  },
  {
    id: "dashboard-communication-client",
    label: "Communication Hub - Client",
    href: "/dashboard/communication/client",
    type: "page",
    keywords: ["dashboard", "communication", "client", "hub"],
    description: "Manage client and supplier collaboration",
    permissionKey: "communicationHubClients",
    featureKey: "communicationHubClients",
  },
  {
    id: "dashboard-communication-collaboration",
    label: "Communication Hub - Collaboration",
    href: "/dashboard/communication/collaboration",
    type: "page",
    keywords: ["dashboard", "communication", "collaboration", "hub"],
    description: "Manage client and supplier collaboration",
    permissionKey: "communicationHubCollaboration",
    featureKey: "communicationHubCollaboration",
  },
  {
    id: "dashboard-communication-internal",
    label: "Communication Hub - Internal",
    href: "/dashboard/communication/internal",
    type: "page",
    keywords: ["dashboard", "communication", "internal", "hub"],
    description: "Manage client and supplier collaboration",
    permissionKey: "communicationHubInternal",
    featureKey: "communicationHubInternal",
  },
  {
    id: "dashboard-employee",
    label: "Directory - Employee",
    href: "/dashboard/employee",
    type: "page",
    keywords: ["dashboard", "employee", "directory"],
    description: "Manage your employees",
    permissionKey: "employeeDirectory",
    featureKey: "employeeDirectory",
  },
  {
    id: "dashboard-estimate",
    label: "Invoices - Estimates",
    href: "/dashboard/estimate",
    type: "page",
    keywords: ["dashboard", "estimate", "invoices", "estimates"],
    description: "View and manage all your estimates.",
    permissionKey: "estimatesInvoices",
    featureKey: "estimateInvoices",
  },
  {
    id: "dashboard-estimate-canned",
    label: "Invoices - Canned",
    href: "/dashboard/estimate/canned",
    type: "page",
    keywords: ["dashboard", "estimate", "canned", "invoices"],
    description: "Manage your canned estimates",
    permissionKey: "estimatesInvoices",
    featureKey: "estimateInvoices",
  },
  {
    id: "dashboard-estimate-create",
    label: "Invoices - Create Estimates",
    href: "/dashboard/estimate/create",
    type: "page",
    keywords: ["dashboard", "estimate", "create", "invoices", "estimates"],
    description: "Create new estimate",
    permissionKey: "estimatesInvoices",
    featureKey: "estimateInvoices",
  },
  {
    id: "dashboard-estimate-invoices",
    label: "Invoices",
    href: "/dashboard/estimate/invoices",
    type: "page",
    keywords: ["dashboard", "estimate", "invoices"],
    description: "View and manage all your invoices.",
    permissionKey: "estimatesInvoices",
    featureKey: "estimateInvoices",
  },
  {
    id: "dashboard-estimate-templates",
    label: "Invoices - Templates",
    href: "/dashboard/estimate/templates",
    type: "page",
    keywords: ["dashboard", "estimate", "templates", "invoices"],
    description: "Manage and customize your invoice templates.",
    permissionKey: "estimatesInvoices",
    featureKey: "estimateInvoices",
  },
  {
    id: "dashboard-estimate-templates-create",
    label: "Invoices - Create Template",
    href: "/dashboard/estimate/templates/create",
    type: "page",
    keywords: [
      "dashboard",
      "estimate",
      "templates",
      "create",
      "invoices",
      "template",
    ],
    description: "Create a new template",
    permissionKey: "estimatesInvoices",
    featureKey: "estimateInvoices",
  },
  {
    id: "dashboard-fleet",
    label: "Directory - Fleet",
    href: "/dashboard/fleet",
    type: "page",
    keywords: ["dashboard", "fleet", "directory"],
    description: "Manage your fleets",
    permissionKey: "fleetDirectory",
    featureKey: "fleetDirectory",
  },
  {
    id: "dashboard-inventory",
    label: "Inventory",
    href: "/dashboard/inventory",
    type: "page",
    keywords: ["dashboard", "inventory"],
    description: "Manage your inventory, products, and supplies",
    permissionKey: ["inventoryAllViewOnly", "inventoryAll"],
    featureKey: "inventory",
  },
  {
    id: "dashboard-inventory-camera",
    label: "Inventory - QR Scanner",
    href: "/dashboard/inventory/camera",
    type: "page",
    keywords: ["dashboard", "inventory", "camera", "scanner"],
    description: "Scan QR codes to quickly find and manage inventory items",
    permissionKey: "inventoryAll",
    featureKey: "inventory",
  },
  {
    id: "dashboard-inventory-vendor",
    label: "Inventory - Vendor",
    href: "/dashboard/inventory/vendor",
    type: "page",
    keywords: ["dashboard", "inventory", "vendor"],
    description: "Manage your vendors",
    permissionKey: "inventoryAll",
    featureKey: "inventory",
  },
  {
    id: "dashboard-payments",
    label: "Payments",
    href: "/dashboard/payments",
    type: "page",
    keywords: ["dashboard", "payments"],
    description: "View and manage all your payments.",
    permissionKey: "payments",
    featureKey: "payments",
  },
  {
    id: "dashboard-pipeline-sales-lead",
    label: "Sales Leads",
    href: "/dashboard/pipeline/sales/lead",
    type: "page",
    keywords: ["dashboard", "pipeline", "sales", "lead", "leads"],
    description: "View and manage your sales leads",
    permissionKey: "salesPipeline",
    featureKey: "salesPipeline",
  },
  {
    id: "dashboard-pipeline-sales-pipeline",
    label: "Pipelines - Sales Pipeline",
    href: "/dashboard/pipeline/sales/pipeline",
    type: "page",
    keywords: ["dashboard", "pipeline", "sales", "pipelines"],
    description: "Manage your sales pipeline",
    permissionKey: "salesPipeline",
    featureKey: "salesPipeline",
  },
  {
    id: "dashboard-pipeline-shop-pipeline",
    label: "Pipelines - Shop Pipeline",
    href: "/dashboard/pipeline/shop/pipeline",
    type: "page",
    keywords: ["dashboard", "pipeline", "shop", "pipelines"],
    description: "Manage your shop pipeline",
    permissionKey: "shopPipeline",
    featureKey: "shopPipeline",
  },
  {
    id: "dashboard-pipeline-shop-workorder",
    label: "Work Orders",
    href: "/dashboard/pipeline/shop/workorder",
    type: "page",
    keywords: ["dashboard", "pipeline", "shop", "workorder", "work", "orders"],
    description: "View and manage your work orders",
    permissionKey: "shopPipeline",
    featureKey: "shopPipeline",
  },
  {
    id: "dashboard-pipeline-team-pipeline",
    label: "Pipelines - Team Pipeline",
    href: "/dashboard/pipeline/team/pipeline",
    type: "page",
    keywords: ["dashboard", "pipeline", "team", "pipelines"],
    description: "Manage your team pipeline",
    permissionKey: "teamPipeline",
    featureKey: "teamPipeline",
  },
  {
    id: "dashboard-pipeline-team-workorder",
    label: "Team Work Orders",
    href: "/dashboard/pipeline/team/workorder",
    type: "page",
    keywords: ["dashboard", "pipeline", "team", "workorder", "work", "orders"],
    description: "View and manage your team work orders",
    permissionKey: "teamPipeline",
    featureKey: "teamPipeline",
  },
  {
    id: "dashboard-reporting-inventory",
    label: "Analytics - Inventory",
    href: "/dashboard/reporting/inventory?view=inventory",
    type: "page",
    keywords: ["dashboard", "reporting", "inventory", "analytics"],
    description: "Analyze inventory performance and profitability",
    permissionKey: ["reporting", "reportingViewOnly"],
    featureKey: "reporting",
  },
  {
    id: "dashboard-reporting-leads",
    label: "Analytics - Leads",
    href: "/dashboard/reporting/leads?view=leads",
    type: "page",
    keywords: ["dashboard", "reporting", "leads", "analytics"],
    description: "Analyze lead generation and conversion performance",
    permissionKey: ["reporting", "reportingViewOnly"],
    featureKey: "reporting",
  },
  {
    id: "dashboard-reporting-payments",
    label: "Analytics - Payments",
    href: "/dashboard/reporting/payments?view=payments",
    type: "page",
    keywords: ["dashboard", "reporting", "payments", "analytics"],
    description: "Analyze payment trends and manage overdue invoices",
    permissionKey: ["reporting", "reportingViewOnly"],
    featureKey: "reporting",
  },
  {
    id: "dashboard-reporting-revenue",
    label: "Analytics - Revenue",
    href: "/dashboard/reporting/revenue?view=revenue",
    type: "page",
    keywords: ["dashboard", "reporting", "revenue", "analytics"],
    description: "Analyze your shop",
    permissionKey: ["reporting", "reportingViewOnly"],
    featureKey: "reporting",
  },
  {
    id: "dashboard-reporting-salesreporting",
    label: "Sales Reporting",
    href: "/dashboard/reporting/salesreporting",
    type: "page",
    keywords: ["dashboard", "reporting", "salesreporting", "sales"],
    description: "View and analyze your sales reports and performance.",
    permissionKey: ["reporting", "reportingViewOnly"],
    featureKey: "reporting",
  },
  {
    id: "dashboard-reporting-teams",
    label: "Analytics - Teams",
    href: "/dashboard/reporting/teams?view=teams",
    type: "page",
    keywords: ["dashboard", "reporting", "teams", "analytics"],
    description: "Manage employee performance and payouts",
    permissionKey: ["reporting", "reportingViewOnly"],
    featureKey: "reporting",
  },
  {
    id: "dashboard-reporting-technicianreporting",
    label: "Technician Reporting",
    href: "/dashboard/reporting/technicianreporting",
    type: "page",
    keywords: ["dashboard", "reporting", "technicianreporting", "technician"],
    description: "View and analyze technician performance and reports.",
    permissionKey: ["reporting", "reportingViewOnly"],
    featureKey: "reporting",
  },
  {
    id: "dashboard-resources",
    label: "Resource",
    href: "/dashboard/resources",
    type: "page",
    keywords: ["dashboard", "resources", "resource"],
    description: "View and manage your resources.",
  },
  {
    id: "dashboard-resources-automation",
    label: "Automation Overview",
    href: "/dashboard/resources/automation",
    type: "page",
    keywords: ["dashboard", "resources", "automation", "overview"],
    description: "An overview of automation principles and practices.",
  },
  {
    id: "dashboard-resources-communication",
    label: "Communication Hub Overview",
    href: "/dashboard/resources/communication",
    type: "page",
    keywords: ["dashboard", "resources", "communication", "hub", "overview"],
    description: "Get an overview of the communication hub and its features.",
  },
  {
    id: "dashboard-resources-directory",
    label: "Directory Overview",
    href: "/dashboard/resources/directory",
    type: "page",
    keywords: ["dashboard", "resources", "directory", "overview"],
    description: "An overview of the directory structure and organization.",
  },
  {
    id: "dashboard-resources-estimates_invoices",
    label: "Estimates & Invoices Overview",
    href: "/dashboard/resources/estimates_invoices",
    type: "page",
    keywords: [
      "dashboard",
      "resources",
      "estimates invoices",
      "estimates",
      "invoices",
      "overview",
    ],
    description:
      "An overview of estimates and invoices principles and practices.",
  },
  {
    id: "dashboard-resources-inventory",
    label: "Inventory Overview",
    href: "/dashboard/resources/inventory",
    type: "page",
    keywords: ["dashboard", "resources", "inventory", "overview"],
    description: "An overview of inventory principles and practices.",
  },
  {
    id: "dashboard-resources-lead",
    label: "Lead Overview",
    href: "/dashboard/resources/lead",
    type: "page",
    keywords: ["dashboard", "resources", "lead", "overview"],
    description: "An overview of lead principles and practices.",
  },
  {
    id: "dashboard-resources-payments",
    label: "Payments Overview",
    href: "/dashboard/resources/payments",
    type: "page",
    keywords: ["dashboard", "resources", "payments", "overview"],
    description: "An overview of payments principles and practices.",
  },
  {
    id: "dashboard-resources-pipeline",
    label: "Learn How to Use the AutoWorx Pipeline",
    href: "/dashboard/resources/pipeline",
    type: "page",
    keywords: ["dashboard", "resources", "pipeline", "learn", "autoworx"],
    description:
      "Discover tutorials and guides to help you navigate and utilize the AutoWorx pipeline effectively. From lead tracking to sales forecasting, we",
  },
  {
    id: "dashboard-resources-reporting",
    label: "Reporting Overview",
    href: "/dashboard/resources/reporting",
    type: "page",
    keywords: ["dashboard", "resources", "reporting", "overview"],
    description: "An overview of reporting principles and practices.",
  },
  {
    id: "dashboard-resources-settings",
    label: "Settings Overview",
    href: "/dashboard/resources/settings",
    type: "settings",
    keywords: ["dashboard", "resources", "settings", "overview"],
    description: "An overview of settings principles and practices.",
  },
  {
    id: "dashboard-resources-task_management",
    label: "Task Management Resources | AutoWorx",
    href: "/dashboard/resources/task_management",
    type: "page",
    keywords: [
      "dashboard",
      "resources",
      "task management",
      "task",
      "management",
      "autoworx",
    ],
    description:
      "Explore the various resources available for managing your tasks effectively. Learn about task management principles, best practices, and collaboration techniques.",
  },
  {
    id: "dashboard-send",
    label: "Send Notification",
    href: "/dashboard/send",
    type: "page",
    keywords: ["dashboard", "send", "notification"],
    description: "Send and manage notifications to your team and clients.",
  },
  {
    id: "dashboard-settings-automation",
    label: "Settings - Automation",
    href: "/dashboard/settings/automation",
    type: "settings",
    keywords: ["dashboard", "settings", "automation"],
    description: "Configure automation settings",
    permissionKey: "businessSettings",
    featureKey: "automation",
  },
  {
    id: "dashboard-settings-billing",
    label: "Settings - Billing",
    href: "/dashboard/settings/billing",
    type: "settings",
    keywords: ["dashboard", "settings", "billing"],
    description: "Manage your billing settings",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-business",
    label: "Settings - Business",
    href: "/dashboard/settings/business",
    type: "settings",
    keywords: ["dashboard", "settings", "business"],
    description: "Manage your business",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-calendar",
    label: "Settings - Calendar",
    href: "/dashboard/settings/calendar",
    type: "settings",
    keywords: ["dashboard", "settings", "calendar"],
    description: "Configure calendar settings",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-communications",
    label: "Settings - Communications",
    href: "/dashboard/settings/communications",
    type: "settings",
    keywords: ["dashboard", "settings", "communications"],
    description: "Configure communications settings",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-estimates",
    label: "Settings - Estimates",
    href: "/dashboard/settings/estimates",
    type: "settings",
    keywords: ["dashboard", "settings", "estimates"],
    description: "Configure estimates and invoices",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-leadgeneration",
    label: "Settings - Lead Generation",
    href: "/dashboard/settings/leadgeneration",
    type: "settings",
    keywords: ["dashboard", "settings", "leadgeneration", "lead", "generation"],
    description: "Configure lead generation settings",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-my-account",
    label: "Settings - My Account",
    href: "/dashboard/settings/my-account",
    type: "settings",
    keywords: ["dashboard", "settings", "my account", "account"],
    description: "Manage your account",
  },
  {
    id: "dashboard-settings-networks",
    label: "Settings - Networks",
    href: "/dashboard/settings/networks",
    type: "settings",
    keywords: ["dashboard", "settings", "networks"],
    description: "Manage your networks",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-notifications",
    label: "Settings - Notifications",
    href: "/dashboard/settings/notifications",
    type: "settings",
    keywords: ["dashboard", "settings", "notifications"],
    description: "Manage your notifications",
  },
  {
    id: "dashboard-settings-payments",
    label: "Settings - Payments",
    href: "/dashboard/settings/payments",
    type: "settings",
    keywords: ["dashboard", "settings", "payments"],
    description: "Configure payment gateways and integrations",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-payments-webhook-events",
    label: "Dashboard › Settings › Payments › Webhook Events",
    href: "/dashboard/settings/payments/webhook-events",
    type: "settings",
    keywords: [
      "dashboard",
      "settings",
      "payments",
      "webhook events",
      "webhook",
      "events",
    ],
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-sales-agent",
    label: "Settings - Sales Agent",
    href: "/dashboard/settings/sales-agent",
    type: "settings",
    keywords: ["dashboard", "settings", "sales agent", "sales", "agent"],
    description: "Configure sales agent settings",
    permissionKey: "businessSettings",
    featureKey: "sales-agent",
  },
  {
    id: "dashboard-settings-sales-agent-ai-settings",
    label: "Settings - Sales Agent AI",
    href: "/dashboard/settings/sales-agent/ai-settings",
    type: "settings",
    keywords: [
      "dashboard",
      "settings",
      "sales agent",
      "ai settings",
      "sales",
      "agent",
    ],
    description: "Configure AI settings for your sales agent",
    permissionKey: "businessSettings",
    featureKey: "sales-agent",
  },
  {
    id: "dashboard-settings-security",
    label: "Settings - Security",
    href: "/dashboard/settings/security",
    type: "settings",
    keywords: ["dashboard", "settings", "security"],
    description: "Configure security settings",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-team-management",
    label: "Settings - Team Management",
    href: "/dashboard/settings/team-management",
    type: "settings",
    keywords: [
      "dashboard",
      "settings",
      "team management",
      "team",
      "management",
    ],
    description: "Manage your team and employees",
    permissionKey: "businessSettings",
    featureKey: "businessSettings",
  },
  {
    id: "dashboard-settings-virtual-shop-configure",
    label: "Settings - Virtual Shop Configure",
    href: "/dashboard/settings/virtual-shop-configure",
    type: "settings",
    keywords: [
      "dashboard",
      "settings",
      "virtual shop configure",
      "virtual",
      "shop",
      "configure",
    ],
    description: "Configure virtual shop settings",
    permissionKey: "businessSettings",
    featureKey: "virtual-shop",
  },
  {
    id: "dashboard-settings-virtual-shop-configure-shops-create",
    label: "Settings - Create Shop",
    href: "/dashboard/settings/virtual-shop-configure/shops/create",
    type: "settings",
    keywords: [
      "dashboard",
      "settings",
      "virtual shop configure",
      "shops",
      "create",
      "shop",
    ],
    description: "Set up and configure your virtual shop.",
    permissionKey: "businessSettings",
    featureKey: "virtual-shop",
  },
  {
    id: "dashboard-virtual-shop-admin",
    label: "Virtual Shop Admin",
    href: "/dashboard/virtual-shop/admin",
    type: "page",
    keywords: ["dashboard", "virtual shop", "admin", "virtual", "shop"],
    description: "Virtual shop admin",
    featureKey: "virtual-shop",
  },
  {
    id: "dashboard-virtual-shop-admin-service-create",
    label: "Virtual Shop - Create Service",
    href: "/dashboard/virtual-shop/admin/service/create",
    type: "page",
    keywords: [
      "dashboard",
      "virtual shop",
      "admin",
      "service",
      "create",
      "virtual",
      "shop",
    ],
    description: "Create or edit a virtual shop service",
    featureKey: "virtual-shop",
  },
  {
    id: "dashboard-visualization",
    label: "Visualization",
    href: "/dashboard/visualization",
    type: "page",
    keywords: ["dashboard", "visualization"],
    description: "Visualize car wraps",
    permissionKey: "visualization",
  },
  {
    id: "dashboard-zap",
    label: "Zapier Data",
    href: "/dashboard/zap",
    type: "page",
    keywords: ["dashboard", "zap", "zapier", "data"],
  },
];

// 66 route(s) registered
