[phases.setup]
nixPkgs = ['nodejs_20', 'bash', 'npm', 'openssl']

[phases.install]
cmds = [
  'rm -rf node_modules package-lock.json',  # 👈 Delete node_modules & lock file
  'npm i --legacy-peer-deps'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'