export const PUBLIC_ROUTES = ["/login", "/register", "/forgot-password", "/"];

export const PUBLIC_API_ROUTES = [
  "/api/auth/login",
  "/api/auth/register",
  "/api/auth/forgot-password",
  "/api/auth/reset-password",
  "/api/auth/forgot-password/verify-otp",
  "/api/auth/refresh-token",
  "/api/auth/providers",
  "/api/auth/signin",
  "/api/auth/callback/credentials",
  "/api/auth/csrf",
  "/api/sales-agent",
  "/api/ai-train-company",
  "/api/notifications/client-abuse",
  // Webhook endpoints
  "/api/meta/webhook",
  "/api/pusher/collaboration",
  "/api/stripe/invoice-pay-hook",
  "/api/twilio/token",
  "/api/twilio/register-voip",
  "/api/infobip",
  "/api/lead-generate",
  "/api/authorize-net/webhook",
  "/api/platform/webhook",
  "/api/infobip/mms/receive",
  "/api/infobip/sms/receive",
  "/api/infobip/email/receive",
  "/api/twilio/call-recording",
  "/api/twilio/call-state",
  "/api/twilio/call-status",
  "/api/twilio/incoming",
  "/api/twilio/receive",
  "/api/twilio/whisper",
  "/api/invoice/track-view",
  "/api/upload",
  "/api/communication/client-hub/send-twilio-message",
  // Virtual shop public storefront read endpoints
  "/api/virtual-shop/shop-services",
  "/api/virtual-shop/shop-services/categories",
  "/api/virtual-shop/appointment-slots",
  // virtual-shop public route
  "/api/virtual-shop/buy-gift-card",
  "/api/virtual-shop/service-booking",
  "/api/virtual-shop/issued-gift-card",
  "/api/virtual-shop/gift-card-settings",
  // gift card public route
  "/api/virtual-shop/issued-gift-card/check-balance",
  "/api/virtual-shop/issued-gift-card/reload",
  "/api/virtual-shop/issued-gift-card/reload/confirmation",
  "/api/virtual-shop/issued-gift-card/reload-payment/initiate",
  "/api/virtual-shop/gift-card-settings/public",
  "/api/virtual-shop/gift-card-payment/initiate",
  "/api/virtual-shop/gift-card-payment/confirmation",
  "/api/virtual-shop/gift-card-templates/public",
  "/api/virtual-shop/client-lookup/by-phone",
  "/api/virtual-shop/service-booking/hold",
  "/api/virtual-shop/emergency-requests",
];

export const PUBLIC_DYNAMIC_API_ROUTES = [
  "/api/infobip/sms/receive/:companyIds",
  "/api/twilio/sms-receive/:companyIds",
  "/api/twilio/call-recording/:recordingSid",
  "/api/admin/client/:id/sales-agent",
  // Public shop resolve by subdomain slug
  "/api/virtual-shop/configure/subdomain/:slug",
];
