import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { z } from "zod";
import moment from "moment";
import { errorHandler } from "@/error-boundary/globalErrorHandler";
import { AppError } from "@/error-boundary/error";

const holdSlotSchema = z.object({
  shopId: z.union([z.string(), z.number()]).transform(Number),
  sessionToken: z.string().min(1, "Session Token is required"),
  date: z.string(),
  startTime: z.string(),
  duration: z.number().optional().default(30),
});

/**
 * @swagger
 * /api/virtual-shop/service-booking/hold:
 *   post:
 *     summary: Temporarily hold a time slot to prevent double booking
 *     description: |
 *       Acquires a 15-minute temporary hold on the requested shop time slot for the given
 *       session token. A database-level row lock (`SELECT FOR UPDATE`) is used to serialize
 *       concurrent requests, ensuring no two users can hold the same slot at the same instant.
 *
 *       - Expired holds are pruned automatically on every call.
 *       - If the same `sessionToken` already holds a slot, that hold is replaced with the new one.
 *       - The frontend must pass the same `sessionToken` in the final booking request so the hold
 *         is recognised and cleared upon successful booking.
 *     tags:
 *       - Virtual Shop
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - shopId
 *               - sessionToken
 *               - date
 *               - startTime
 *             properties:
 *               shopId:
 *                 type: integer
 *                 description: The ID of the shop whose slot is being held.
 *                 example: 1
 *               sessionToken:
 *                 type: string
 *                 description: A unique session identifier generated by the frontend for this booking session.
 *                 example: "k7x2m9qpz3b4a8"
 *               date:
 *                 type: string
 *                 format: date
 *                 description: The date of the slot to hold (YYYY-MM-DD).
 *                 example: "2026-05-10"
 *               startTime:
 *                 type: string
 *                 description: The start time of the slot in HH:mm (24-hour) format.
 *                 example: "10:30"
 *               duration:
 *                 type: integer
 *                 description: Total duration of all selected services in minutes. Defaults to 30 if omitted.
 *                 example: 90
 *     responses:
 *       200:
 *         description: Slot successfully held for 15 minutes.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: "Slot successfully held for 15 minutes"
 *                 data:
 *                   type: object
 *                   properties:
 *                     id:
 *                       type: integer
 *                       description: The hold record ID.
 *                       example: 42
 *                     shopId:
 *                       type: integer
 *                       example: 1
 *                     sessionToken:
 *                       type: string
 *                       example: "k7x2m9qpz3b4a8"
 *                     date:
 *                       type: string
 *                       format: date-time
 *                       example: "2026-05-10T00:00:00.000Z"
 *                     startTime:
 *                       type: string
 *                       example: "10:30"
 *                     endTime:
 *                       type: string
 *                       description: Computed end time based on startTime + duration.
 *                       example: "12:00"
 *                     expiresAt:
 *                       type: string
 *                       format: date-time
 *                       description: The timestamp at which this hold expires (15 minutes from now).
 *                       example: "2026-05-10T10:45:00.000Z"
 *                     createdAt:
 *                       type: string
 *                       format: date-time
 *                       example: "2026-05-10T10:30:00.000Z"
 *       400:
 *         description: |
 *           Bad Request – the slot is no longer available because it is already booked or
 *           held by another session, or required fields are missing/invalid.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: "This exact slot was just reserved or is no longer available."
 *       404:
 *         description: Shop or shop booking settings not found.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: "Shop not found"
 *       500:
 *         description: Internal Server Error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: "Internal server error"
 */
export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { shopId, sessionToken, date, startTime, duration } =
      await holdSlotSchema.parseAsync(body);

    const result = await db.$transaction(async (tx) => {
      // 1. Lock ShopBookingSetting to serialize requests for this shop
      await tx.$executeRawUnsafe(
        'SELECT 1 FROM "shop_booking_settings" WHERE "shop_id" = $1 FOR UPDATE',
        shopId,
      );

      // 2. Fetch Shop and ShopBookingSetting
      const shop = await tx.shop.findUnique({
        where: { id: shopId },
      });

      if (!shop) {
        throw new AppError(404, "Shop not found");
      }

      const bookingSettings = await tx.shopBookingSetting.findUnique({
        where: { shopId },
      });

      if (!bookingSettings) {
        throw new AppError(404, "Shop booking settings not found");
      }

      // 3. Clear expired holds to free up capacity
      await tx.shopSlotHold.deleteMany({
        where: {
          shopId,
          expiresAt: { lt: new Date() },
        },
      });

      // 4. Check Capacity
      // Calculate End Time
      const proposedEndMoment = moment
        .utc(`${date} ${startTime}`, "YYYY-MM-DD HH:mm")
        .add(duration, "minutes");

      // Check existing appointments overlap (includes multi-day via endDate)
      const startOfSelectedDay = new Date(`${date}T00:00:00.000Z`);
      const startOfNextDay = new Date(
        startOfSelectedDay.getTime() + 24 * 60 * 60 * 1000,
      );

      const existingAppointments = await tx.appointment.findMany({
        where: {
          companyId: shop.companyId,
          AND: [
            { date: { lt: startOfNextDay } },
            {
              OR: [
                { endDate: { gte: startOfSelectedDay } },
                {
                  endDate: null,
                  date: { gte: startOfSelectedDay },
                },
              ],
            },
          ],
        },
        select: { date: true, endDate: true, startTime: true, endTime: true },
      });

      // Check existing active holds overlap
      const activeHolds = await tx.shopSlotHold.findMany({
        where: { shopId, date: new Date(date) },
        select: { startTime: true, endTime: true, sessionToken: true },
      });

      // Slot logic identical to what we fixed in booking
      const proposedStartMoment = moment.utc(
        `${date} ${startTime}`,
        "YYYY-MM-DD HH:mm",
      );

      const overlappingAppointments = existingAppointments.filter((app) => {
        if (!app.startTime || !app.endTime || !app.date) return false;
        const startDateStr = moment.utc(app.date).format("YYYY-MM-DD");
        const endAnchorDate = app.endDate ?? app.date;
        const endDateStr = moment.utc(endAnchorDate).format("YYYY-MM-DD");

        const appStartMoment = moment.utc(
          `${startDateStr} ${app.startTime}`,
          "YYYY-MM-DD HH:mm",
        );
        const appEndMoment = moment.utc(
          `${endDateStr} ${app.endTime}`,
          "YYYY-MM-DD HH:mm",
        );
        return (
          proposedEndMoment.isAfter(appStartMoment) &&
          proposedStartMoment.isBefore(appEndMoment)
        );
      });

      const overlappingHolds = activeHolds.filter((hold) => {
        if (hold.sessionToken === sessionToken) return false; // Ignore same session updating its hold
        if (!hold.startTime || !hold.endTime) return false;
        const holdStartMoment = moment.utc(
          `${date} ${hold.startTime}`,
          "YYYY-MM-DD HH:mm",
        );
        const holdEndMoment = moment.utc(
          `${date} ${hold.endTime}`,
          "YYYY-MM-DD HH:mm",
        );
        return (
          proposedEndMoment.isAfter(holdStartMoment) &&
          proposedStartMoment.isBefore(holdEndMoment)
        );
      });

      const totalConcurrent =
        overlappingAppointments.length + overlappingHolds.length;

      if (
        totalConcurrent >=
        (bookingSettings.isStackingEnabled ? bookingSettings.stackingLimit : 1)
      ) {
        throw new AppError(
          400,
          "This exact slot was just reserved or is no longer available.",
        );
      }

      // 5. Create or Update Hold
      // If the sessionToken already has a hold, delete it or extend it
      await tx.shopSlotHold.deleteMany({
        where: { shopId, sessionToken },
      });

      const newHold = await tx.shopSlotHold.create({
        data: {
          shopId,
          sessionToken,
          date: new Date(date),
          startTime,
          endTime: proposedEndMoment.format("HH:mm"),
          expiresAt: moment().add(15, "minutes").toDate(),
        },
      });

      return newHold;
    });

    return NextResponse.json({
      success: true,
      message: "Slot successfully held for 15 minutes",
      data: result,
    });
  } catch (error: any) {
    const formattedError = errorHandler(error);
    return NextResponse.json(
      {
        success: false,
        message: formattedError.message,
        errorDetails: formattedError,
      },
      { status: formattedError.statusCode },
    );
  }
}

/**
 * @swagger
 * /api/virtual-shop/service-booking/hold:
 *   delete:
 *     summary: Release a slot hold immediately
 *     description: |
 *       Deletes the temporary slot hold for the given `sessionToken` and `shopId`.
 *       Should be called by the frontend when:
 *       - The user clicks the Back button on the Checkout page.
 *       - The browser window/tab is closed (via `navigator.sendBeacon`).
 *       - The user explicitly cancels the booking.
 *       Releasing the hold instantly makes the slot visible to other users.
 *     tags:
 *       - Virtual Shop
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - shopId
 *               - sessionToken
 *             properties:
 *               shopId:
 *                 type: integer
 *                 description: The ID of the shop whose hold should be released.
 *                 example: 1
 *               sessionToken:
 *                 type: string
 *                 description: The session token that owns the hold.
 *                 example: "k7x2m9qpz3b4a8"
 *     responses:
 *       200:
 *         description: Hold released successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: "Slot hold released successfully"
 *       400:
 *         description: Missing required fields.
 *       500:
 *         description: Internal Server Error.
 */
export async function DELETE(req: Request) {
  try {
    const body = await req.json();
    const schema = z.object({
      shopId: z.union([z.string(), z.number()]).transform(Number),
      sessionToken: z.string().min(1, "Session Token is required"),
    });
    const { shopId, sessionToken } = await schema.parseAsync(body);

    await db.shopSlotHold.deleteMany({
      where: { shopId, sessionToken },
    });

    return NextResponse.json({
      success: true,
      message: "Slot hold released successfully",
    });
  } catch (error: any) {
    const formattedError = errorHandler(error);
    return NextResponse.json(
      { success: false, message: formattedError.message },
      { status: formattedError.statusCode },
    );
  }
}
