name: Deploy production

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}" >> .env
          echo "PUSHER_ID=${{ secrets.PUSHER_ID }}" >> .env
          echo "PUSHER_KEY=${{ secrets.PUSHER_KEY }}" >> .env
          echo "PUSHER_SECRET=${{ secrets.PUSHER_SECRET }}" >> .env
          echo "NEXT_PUBLIC_PUSHER_INSTANCE_ID=${{ secrets.NEXT_PUBLIC_PUSHER_INSTANCE_ID }}" >> .env
          echo "PUSHER_PRIMARY_KEY=${{ secrets.PUSHER_PRIMARY_KEY }}" >> .env
          echo "NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}" >> .env
          echo "PUSHER_CLUSTER=${{ secrets.PUSHER_CLUSTER }}" >> .env
          echo "NEXT_PUBLIC_PUSHER_KEY=${{ secrets.NEXT_PUBLIC_PUSHER_KEY }}" >> .env
          echo "NEXT_PUBLIC_PUSHER_CLUSTER=${{ secrets.NEXT_PUBLIC_PUSHER_CLUSTER }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GMAIL_CLIENT_ID=${{ secrets.GMAIL_CLIENT_ID }}" >> .env
          echo "GMAIL_CLIENT_SECRET=${{ secrets.GMAIL_CLIENT_SECRET }}" >> .env
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
          echo "TWILIO_API_KEY_SID=${{ secrets.TWILIO_API_KEY_SID }}" >> .env
          echo "TWILIO_API_KEY_SECRET=${{ secrets.TWILIO_API_KEY_SECRET }}" >> .env
          echo "TWILIO_TWIML_APP_SID=${{ secrets.TWILIO_TWIML_APP_SID }}" >> .env
          echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> .env
          echo "ASANA_PERSONAL_TOKEN=${{ secrets.ASANA_PERSONAL_TOKEN }}" >> .env
          echo "ASANA_WORKSPACE=${{ secrets.ASANA_WORKSPACE }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          echo "AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}" >> .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env
          echo "NEXT_PUBLIC_STRIPE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_STRIPE_CLIENT_ID }}" >> .env
          echo "ACCESS_CODE=${{ secrets.ACCESS_CODE }}" >> .env
          echo "NEXT_PUBLIC_ONESIGNAL_APP_ID=${{ secrets.NEXT_PUBLIC_ONESIGNAL_APP_ID }}" >> .env
          echo "ONESIGNAL_AUTHORIZATION_KEY=${{ secrets.ONESIGNAL_AUTHORIZATION_KEY }}" >> .env
          echo "NEXT_PUBLIC_ONESIGNAL_SAFARI_WEB_ID=${{ secrets.NEXT_PUBLIC_ONESIGNAL_SAFARI_WEB_ID }}" >> .env
          echo "MAILGUN_USERNAME=${{ secrets.MAILGUN_USERNAME }}" >> .env
          echo "MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}" >> .env
          echo "MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }}" >> .env
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/autworx-production-1 .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/autworx-production-1:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/autworx-production-1:latest
      - name: Delete existing container
        run: docker rm -f autworx-production-1
      - name: Run the container
        run: docker run -d --restart always -p 3000:3000 --name autworx-production-1 ${{ secrets.DOCKER_USERNAME }}/autworx-production-1
      - name: Wait for the container to be ready
        run: sleep 60
      - name: Call Cron API
        run: curl -v -X GET "https://autoworx.tech/api/crons"
