name: TypeScript Check

on:
  pull_request:
    branches: [main, development]
  push:
    branches: [main, development]

jobs:
  typescript-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Change from "18" to "20" (or "22" for the current LTS)
          node-version: "22"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Prisma Generate
        run: yarn prisma generate
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/postgres"

      - name: TypeScript check
        run: yarn tsc --noEmit
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
